version: '3.8'

services:
  mysql_container:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: caltizm
      MYSQL_USER: caltizm
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "mysql_container", "-u", "root", "-proot1234" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - caltizm_network

  spring_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring_app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql_container:3306/caltizm
      SPRING_DATASOURCE_USERNAME: caltizm
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    volumes:
      - ./upload:/app/upload  # 호스트의 ./upload를 컨테이너의 /app/upload에 연결
    depends_on:
      mysql_container:
        condition: service_healthy
    networks:
      - caltizm_network

volumes:
  db_data:

networks:
  caltizm_network: