name: CI/CD for Final Project

on:
  push:
    branches:
      - main  # main 브랜치에 푸쉬될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. SSH 설정
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      # 3. EC2에 SSH 연결 후 명령 실행
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@43.201.100.240 << 'EOF'
            cd /home/ec2-user/Final-Project
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
      #되라제발